#!/bin/bash

if [ -e ./auto/Net/Gnats/autosplit.ix  ]
then
    rm -f auto/Net/Gnats/autosplit.ix
fi


if [ -e ./auto/Net/Gnats/PR/autosplit.ix  ]
then
    rm -f auto/Net/Gnats/PR/autosplit.ix
fi


perl -e 'use AutoSplit; autosplit($ARGV[0], $ARGV[1], 0, 1, 1)' Net/Gnats.pm
perl -e 'use AutoSplit; autosplit($ARGV[0], $ARGV[1], 0, 1, 1)' Net/Gnats/PR.pm


cp -r ./lib/auto .
cp -r ./lib/auto .

rm ./lib/auto/Net/Gnats/autosplit.ix 
rm ./lib/auto/Net/Gnats/PR/autosplit.ix 

rm -ri ./lib
